/**
 * Build step.
 *
 *  1. Bundle `view/bridge.ts` (the MCP Apps relay) into one IIFE and emit it as
 *     a JS string module, so `view.mjs` can inline it into the `ui://` resource.
 *     Inlining means the resource declares no `script-src` origins at all.
 *  2. Copy the Flutter web build into `public/app`, dropping the debug symbol
 *     files — they are a third of the output and nothing fetches them.
 *
 * `--with-flutter` runs `flutter build web` first.
 */

import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import {
  cpSync,
  existsSync,
  mkdirSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import * as esbuild from "esbuild";

const here = dirname(fileURLToPath(import.meta.url));
const appDir = resolve(here, "../app");
const flutterOut = join(appDir, "build/web");
const publicApp = join(here, "public/app");

if (process.argv.includes("--with-flutter")) {
  console.log("• flutter build web");
  execFileSync(
    process.env.FLUTTER ?? "flutter",
    [
      "build", "web",
      "--release",
      "--pwa-strategy=none",
      "--no-web-resources-cdn",
      "--no-wasm-dry-run",
      "--base-href", "/app/",
    ],
    { cwd: appDir, stdio: "inherit" },
  );
}

// ---------------------------------------------------------------------------
// 1. The view bridge
// ---------------------------------------------------------------------------

console.log("• bundling view/bridge.ts");
const bundle = await esbuild.build({
  entryPoints: [join(here, "view/bridge.ts")],
  bundle: true,
  minify: true,
  format: "iife",
  target: ["es2022"],
  platform: "browser",
  write: false,
  legalComments: "none",
});

const source = bundle.outputFiles[0].text;
const generatedDir = join(here, "src/generated");
mkdirSync(generatedDir, { recursive: true });
// A short content hash of the bundle. The view stamps it into every beacon and
// every diagnostic report, which is the only way to tell — from outside a host
// that caches resources — whether what rendered is what we deployed.
const buildId = createHash("sha256").update(source).digest("hex").slice(0, 8);

writeFileSync(
  join(generatedDir, "view-bridge.mjs"),
  "// Generated by build.mjs from view/bridge.ts. Do not edit.\n" +
    `export const VIEW_BRIDGE_JS = ${JSON.stringify(source)};\n` +
    `export const VIEW_BUILD_ID = ${JSON.stringify(buildId)};\n`,
);
console.log(`  build ${buildId}`);
console.log(`  ${(source.length / 1024).toFixed(1)} kB inlined`);

// ---------------------------------------------------------------------------
// 1b. The dev host
// ---------------------------------------------------------------------------

console.log("• bundling devhost/host.ts");
await esbuild.build({
  entryPoints: [join(here, "devhost/host.ts")],
  outfile: join(here, "devhost/host.js"),
  bundle: true,
  format: "iife",
  target: ["es2022"],
  platform: "browser",
  sourcemap: false,
  legalComments: "none",
});

// ---------------------------------------------------------------------------
// 2. The Flutter build
// ---------------------------------------------------------------------------

if (!existsSync(flutterOut)) {
  console.warn(
    `! no Flutter build at ${relative(here, flutterOut)} — ` +
      "run with --with-flutter (or `flutter build web` in ../app) before deploying",
  );
} else {
  console.log("• copying the Flutter build into public/app");
  rmSync(publicApp, { recursive: true, force: true });
  mkdirSync(publicApp, { recursive: true });
  cpSync(flutterOut, publicApp, {
    recursive: true,
    filter: (src) => !src.endsWith(".symbols"),
  });
  console.log(`  ${(dirSize(publicApp) / 1024 / 1024).toFixed(1)} MB served from /app/`);
}

function dirSize(dir) {
  let total = 0;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    total += entry.isDirectory() ? dirSize(full) : statSync(full).size;
  }
  return total;
}
